### ISSUE TITLE
Proactive Measures

### ISSUE THREAD

**Issue by is-sim** [MarinoMtz/lorawan_jamming#4]
Hi Marino, sorry for my continuing doubts and perplexities. 
I've tried four different simulations (no proactive measures, only authpre active, only multichannel active, authpre and multichannel both active) and got a bit strange results. 
As you can see from the attached image in the case where authpre is activated I have a strangely high number of success_jm, is this normal behaviour? 
(Initially authpre's code was commented out and automatically raised the number of success_jm to 0)

I also tried another simulation with multichannel active but without tripling the number of jammers and despite this active countermeasure the result obtained was worse than the same simulation without active countermeasures. (image with yellow underlines)

Thank you for your availability
![Confronto 4 simulazioni 30N-1GW-8JM senza commenti](https://user-images.githubusercontent.com/62390749/161514192-8112b7a6-a17c-4903-8de2-f746584bfb0f.jpg)
![Confronto 4 simulazioni 30N-1GW-8JM](https://user-images.githubusercontent.com/62390749/161514498-6560a2b3-1cdf-45f7-8cb6-1e3e11cbfce5.jpg)

**Comment by MarinoMtz** [comment]
The idea of authenticated preambles is that, if a gateway detects that the preamble was compromised it ends the reception rigth after the end of the preamble, so that the reception path can be used for another transmission, and hopefully the packet success probability will increase a litte bit.

The jammer packet's are still in the medium and even if the reception path is free, if the GW takes another packet on the same SF and channel it might still be a destructive collision.

To see if it works, you should launch several iterations (and vary on or two parameters e.g. jammer duty cycle, No. devices, etc) I can't tell you if this is the normal behaviour from a single simulation.

I see though that the values vary from one simulation to another you get more messages and less ED packet losses with authenticated preambles, which is the expected results.

Regarding the success of number of jamming packets, I ddn't verify if the callback still work as expected with auth preambles, Try to verify it

BR

**Comment by is-sim** [comment]
In the case of the multichannel I noticed that you multiply the number of jammers by three, I didn't understand why, could you explain it to me?

**Comment by MarinoMtz** [comment]
I wanted a jammer on the three EU channels
